---
sudo: required
language: python
cache: pip
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo add-apt-repository --yes --update ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install docker-ce ansible
  - ansible --version
  - docker version
install:
  - pip install molecule docker
script:
  - molecule test
