---
sudo: required
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1804 SCENARIO_NAME=default
    - MOLECULE_DISTRO: ubuntu1804 SCENARIO_NAME=no-role
    - MOLECULE_DISTRO: ubuntu1604 SCENARIO_NAME=default
    - MOLECULE_DISTRO: ubuntu1604 SCENARIO_NAME=no-role

before_install:
  - swapoff -a
  - cat ci/daemon.json | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo add-apt-repository --yes ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install docker-ce ansible
  - ansible --version
  - docker version
install:
  - pip install ansible-lint molecule docker
  - ansible-lint --version
script:
  - ansible-lint -x ANSIBLE0016 -x 405 .
  - molecule test --scenario-name $SCENARIO_NAME

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
