---
sudo: required
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1804 SCENARIO_NAME=default DRIVER_NAME=docker
    - MOLECULE_DISTRO: ubuntu1804 SCENARIO_NAME=no-role DRIVER_NAME=docker
    - MOLECULE_DISTRO: ubuntu1604 SCENARIO_NAME=default DRIVER_NAME=docker
    - MOLECULE_DISTRO: ubuntu1604 SCENARIO_NAME=no-role DRIVER_NAME=docker

before_install:
  - swapoff -a
  - ci/install-$DRIVER_NAME.sh
  - ansible --version
install:
  - pip install ansible-lint molecule docker
  - ansible-lint --version
  - molecule --version
script:
  - ansible-lint -x ANSIBLE0016 -x 405 .
  - molecule test --scenario-name $SCENARIO_NAME

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
