---

- name: Wait for all nodes to be ready
  shell: kubectl get nodes
  register: kubectl_nodes
  until: kubectl_nodes.stdout.find('NotReady') == -1
  delay: 1
  retries: 100
  become: false
  when:
    - device_farm_role is defined
    - device_farm_role == 'master'
    - kubernetes_init_stat.stat is defined
    - not kubernetes_init_stat.stat.exists
