---

- name: Install Helm
  become: true
  tasks:

  - stat: path=/usr/local/bin/helm
    register: helm_exists

  - name: Create Helm download folder
    file:
      path=~/helm/
      state=directory
    when: helm_exists.stat.exists == False

  - name: Download and install Helm
    unarchive:
      src: https://storage.googleapis.com/kubernetes-helm/helm-{{helm_version}}-linux-amd64.tar.gz
      remote_src: true
      dest: ~/helm/
    when: helm_exists.stat.exists == False

  - name: Move helm binary
    command: sudo mv ~/helm/linux-amd64/helm /usr/local/bin/helm
    when: helm_exists.stat.exists == False

  - name: Delete Helm download folder
    file:
      path: ~/helm/
      state: absent
    when: helm_exists.stat.exists == False
