---

- name: Prepare a Kubernetes cluster node
  become: yes
  tasks:

  - name: Add the required apt packages
    apt: name={{item}} state=present
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - aptitude

  - name: Loading the br_netfilter kernel module
    modprobe:
     name: br_netfilter
     state: present

  - name: update kernel settings
    sysctl:
     name: net.bridge.bridge-nf-call-iptables
     value: 1
     sysctl_set: yes
     state: present
     reload: yes

  - name: Add Docker apt key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: Add Docker apt repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present
    register: apt_docker

  - name: Add Kubernetes apt key
    apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

  - name: Add Kubernetes apt repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
    register: apt_kubernetes

  - name: Update apt cache
    apt:
     update_cache: yes
    when: apt_docker.changed or apt_kubernetes.changed

  - name: Install Docker
    apt:
     pkg: docker-ce={{docker-version}}
    register: docker_install

  - name: Configure Docker cgroupdriver
    copy:
     content: |
              {
                "exec-opts": ["native.cgroupdriver=cgroupfs"]
              }
     dest: /etc/docker/daemon.json
    register: docker_cgroupdriver

  - name: Restart docker
    service:
     name: docker
     state: restarted
    when: docker_cgroupdriver.changed

  - name: Install Kubernetes kubelet kubeadm kubectl
    apt: name={{item}} state=present
    with_items:
     - kubelet={{kubernetes_version}}-00
     - kubeadm={{kubernetes_version}}-00
     - kubectl={{kubernetes_version}}-00

  - name: Load the required kernel modules
    modprobe: name={{item}} state=present
    with_items:
     - ip_vs
     - ip_vs_rr
     - ip_vs_wrr
     - ip_vs_sh
