---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bionic
    image: ubuntu:18.04
    privileged: true
  - name: xenial
    image: ubuntu:16.04
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0016
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
